from .channel_forward import CHANNEL_FORWARD_ROLESPEC_V1

ROLE_SPECS = {
    CHANNEL_FORWARD_ROLESPEC_V1.role_name: CHANNEL_FORWARD_ROLESPEC_V1,
}

__all__ = ["ROLE_SPECS", "CHANNEL_FORWARD_ROLESPEC_V1"]
